site: liscband.com
title: Lost in Space Blog
greetings: Ay
description: >-
  Welcome to the band blog 👋
lang: en-US
timezone: America/New_York
repo: https://github.com/liscband/liscband.github.io # site repo [optional]
# data-theme: dark # default theme "dark" | "light"
# discus-identifier: ethanexline-com.disqus.com link #old

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://www.liscband.com" # Domain Name of host.
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jemoji

emoji:
  src: "https://github.githubassets.com/images/icons/"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false